services:
    document-service:
      image: document-service
      container_name: document-service
      build:
        context: .
        dockerfile: Dockerfile.prod
      ports:
        - '3002:3002'