services:
  app:
    build: .
    ports:
      - '3002:3002'

  mongo:
    image: mongo
    ports:
      - '27012:27017'
    volumes:
      - type: volume
        source: data
        target: /var/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
volumes:
  data: {}
